---
- name: Configure Activation Keys for Library
  shell: /usr/bin/hammer activation-key create \
         --name "{{ item[0].cv_name }}-Library-KEY" \
         --content-view "{{ item[0].cv_name }}" \
         --lifecycle-environment "Library" \
         --organization "{{ sat_org }}" \
         --unlimited-hosts \
         --description "Library key for {{ item[0].cv_name }}"
  with_nested:
    - "{{ content_views }}"
    - "{{ lifecycle_envs }}"
  register: result
  changed_when:
    - result.rc == 0  #gets enabled
  failed_when:
    - result.rc != 0  #gets enabled
    - result.rc != 65 #already enabled
  tags:
    - activationkeys

- name: Configure Activation Keys for Lifecycle Environments
  shell: /usr/bin/hammer activation-key create \
         --name "{{ item[0].cv_name }}-{{ item[1].name }}-KEY" \
         --content-view "{{ item[0].cv_name }}" \
         --lifecycle-environment "{{ item[1].name }}" \
         --organization "{{ sat_org }}" \
         --unlimited-hosts \
         --description "{{ item[1].label }} key for {{ item[0].cv_name }}"
  with_nested:
    - "{{ content_views }}"
    - "{{ lifecycle_envs }}"
  register: result
  changed_when:
    - result.rc == 0  #gets enabled
  failed_when:
    - result.rc != 0  #gets enabled
    - result.rc != 65 #already enabled
  tags:
    - activationkeys

- name: Enable default repositories for Activation Keys
  shell: for label in $(/usr/bin/hammer --csv activation-key product-content \
         --name "{{ item[0].cv_name }}-{{ item[1].name }}-KEY" \
         --organization "{{ sat_org }}" \
         | grep -v Label | cut -d, -f6);
         do
           /usr/bin/hammer activation-key content-override \
           --content-label ${label} \
           --name "{{ item[0].cv_name }}-{{ item[1].name }}-KEY" \
           --organization "{{ sat_org }}" \
           --value 1;
         done
  with_nested:
    - "{{ content_views }}"
    - "{{ lifecycle_envs }}"
  tags:
    - activationkeys
