---
- name: Configuring Firewall for Satellite Communication
  service:
    state: started
    enabled: yes
    name: firewalld
  tags:
    - firewall

- firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  with_items:
    - RH-Satellite-6
    - tftp
    - dns
    - dhcp
  tags:
    - firewall

- name: Open firewall port for ocp container registry
  firewalld:
    port: 5000/tcp
    permanent: true
    state: enabled
    immediate: true
  tags:
    - firewall

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted
  tags:
    - firewall
