# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
# baseline satellite disk
seconddisk = '/run/media/kpeeples/c95d4664-d61c-4e35-aa97-39c71d568dfc/satellitedisk/SatelliteDisk.vdi'

Vagrant.configure("2") do |config|

    config.vm.define "satellite" do |satellite|
    satellite.vm.box = "generic/rhel7"
    satellite.vm.hostname = 'satellitehost.satellitedomain'
    satellite.vm.box_url = "generic/rhel7"
    satellite.vm.network :private_network, ip: "192.168.11.10"
    satellite.vm.provider :virtualbox do |v|
      unless File.exist?(seconddisk)
        v.customize ['createhd', '--filename', seconddisk, '--variant', 'Fixed', '--size', 200 * 1024]
      end
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 8192]
      v.customize ["modifyvm", :id, "--cpus", 4]
      v.customize ["modifyvm", :id, "--name", "satelliteCREATE"]
      v.customize ['storageattach', :id,  '--storagectl', 'IDE Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', seconddisk]
    end
  end

  # the below is for adding a shared/synced folder
  # config.vm.synced_folder "/run/media/kpeeples/c95d4664-d61c-4e35-aa97-39c71d568dfc/satellitevolume", "/satellitevolume", :mount_options => ["dmode=777", "fmode=666"]
  # config.vm.provision :shell do |shell|
  #   shell.inline = "sudo mount -t vboxsf satellitevolume /satellitevolume"
  #   shell.inline = "sudo chmod 777 /satellitevolume"
  # end
  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.inventory_path = "provisioning/inventory"
    ansible.become = true
    ansible.ask_vault_pass = true
    # ansible.verbose = 'vvvv'
    # ansible.tags = "disconnected"
  end



end
